name: boilerplate-dev

services:
  boilerplate-server:
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./.env
    volumes:
      - ".:/home/app"
      - /home/app/node_modules
    depends_on:
      boilerplate-db:
        condition: service_healthy
    ports:
      - "5050:5050"
    networks:
      - boilerplate-net

  boilerplate-db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - boilerplate-net

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      boilerplate-db:
        condition: service_healthy
    networks:
      - boilerplate-net

volumes:
  db-data:
    driver: local

networks:
  boilerplate-net:
    driver: bridge
