FROM node:22-bookworm-slim

WORKDIR /home/app

RUN apt-get update \
    && apt-get install -y openssl \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx prisma generate

COPY entrypoint.development.sh ./entrypoint.development.sh
RUN chmod +x ./entrypoint.development.sh

EXPOSE 5050

ENTRYPOINT ["./entrypoint.development.sh"]
